
server:
  port: 8443

spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  datasource:
    # 驱动
    # 数据库连接已过时，com.mysql.jdbc.Driver被建议替换为com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.65.198:3306/ces_dev?serverTimezone=UTC&characterEncoding=utf-8
    # 注意修改数据库连接信息
    username: root
    password: root
  # redis
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis:
  # classpath 在这里代表 src 目录
  mapper-locations: classpath:mappers/*.xml
  # 全局的映射，不用在xml文件写实体类的全路径
  type-aliases-package: edu.dlut.ssdut.abilityfosterplatform.model
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#自己修改要保存的文件夹根目录
uploadFile:
  resourceHandler: /uploadFile/**
  location: C:/Users/JK Zhu/Desktop/新建文件夹/ability-foster-platform/src/main/resources/static/uploadFile/

